#!/usr/bin/env python3
"""Refresh the vendored token list from its upstream sources.

Run by hand, never by the app. A token list decides which tokens blocktail
treats as real, so it is a trust input, and a trust input fetched at runtime is
one nobody has read. Vendoring it means every change arrives as a diff that a
person reviews before it ships — and that the app keeps working, identically,
with no network at all.

    python scripts/refresh-token-list.py

Sources follow the token-list standard (https://tokenlists.org): a JSON
document with a `version` and a `tokens` array of `{chainId, address, symbol,
decimals}`. Add more by extending SOURCES; entries are merged, and the first
source to claim an address wins.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

CHAIN_ID = 1  # Ethereum mainnet
OUT = Path(__file__).resolve().parent.parent / "app/chains/ethereum/tokenlist.json"

SOURCES = [
    # Conservative and well curated: the floor, not the ceiling. A wider list
    # recognises more real tokens and also more things that merely got listed.
    ("Uniswap Labs Default", "https://tokens.uniswap.org"),
]


def fetch(url: str) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": "blocktail-refresh"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def main() -> int:
    tokens: dict[str, dict] = {}
    provenance = []

    for name, url in SOURCES:
        document = fetch(url)
        version = document.get("version", {})
        listed = [t for t in document.get("tokens", []) if t.get("chainId") == CHAIN_ID]
        if not listed:
            print(f"{name}: no chain {CHAIN_ID} tokens — refusing to write", file=sys.stderr)
            return 1

        for token in listed:
            address = str(token["address"]).lower()
            if address in tokens:
                continue
            tokens[address] = {
                "symbol": str(token["symbol"]),
                "decimals": int(token["decimals"]),
            }
        provenance.append(
            {
                "name": name,
                "url": url,
                "version": f"{version.get('major', 0)}.{version.get('minor', 0)}"
                f".{version.get('patch', 0)}",
                "tokens": len(listed),
            }
        )
        print(f"{name} v{provenance[-1]['version']}: {len(listed)} mainnet tokens")

    payload = {
        "_comment": (
            "Generated by scripts/refresh-token-list.py. Do not edit by hand — "
            "edit CURATED in known_assets.py for entries no upstream list carries."
        ),
        "chainId": CHAIN_ID,
        "refreshed": datetime.now(UTC).strftime("%Y-%m-%d"),
        "sources": provenance,
        "tokens": dict(sorted(tokens.items())),
    }
    OUT.write_text(json.dumps(payload, indent=1, sort_keys=False) + "\n")
    print(f"wrote {OUT.relative_to(Path.cwd())}: {len(tokens)} tokens")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
